apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::539827877726:role/github-actions-role
      username: github-actions
      groups:
        - system:masters
